# NumPy (Numerical Python)
![](_rsc\numpy.jpg)
## https://numpy.org

Numerical Python, o mejormente conocido como numpy, es una libreria de python open source(codigo libre), que es usado practicamente en todos los campos de ciencia e ingenieria. Es el standard universal para el trabajo con datos numericos en python.

La principal caracteristica de la libreria NumPy es que contiene arrays multidimensionales y matrices como estructuras de datos(OBJETOS), ademas de numerosos metodos que podemos aplicar a dichos arrays para hacer calculos matematicos complejos.

En resumen: NumPy incorpora a python poderosas estructuras de datos, que garantizan calculos efiencientes con arrays y matrices, ademas que vienen incorporados numerosas funciones matematicas de alto nivel que pueden operarse en estos arrays y matrices

In [ ]:
''' 
Primero que todo, debemos instalar la libreria de NumPy, ya que esta
no viene incorporada en el interprete de python, para realizar la
instalacion, debemos ejecutar en nuestro terminal el siguiente comando:

pip install numpy

O simplemente ejecuta esta celda y la descarga se hara automaticamente
'''

!pip install numpy

Una vez instala la libreria, ya podemos usarla en nuestro codigo python, para eso primero debemos importarla

In [1]:
import numpy as np

*Numpy siempre se importa con el alias de `np`, esto con el objetivo de un codigo mas legible, esto es una convencion que todos los programadores en el mundo siguen*

In [16]:
# ahora creemos un array de numpy, esto se hace de la siguiente manera

array = np.array([10,20,30,40,50])

type(array)

numpy.ndarray

In [ ]:
# podemos crear un array tambien con un rango

array1 = np.arange(5)

print(array1)

#### `np.linspace()`

In [ ]:
#con linspace podemos crear un intervalo lo mas denso que querramos.

l = np.linspace(start=0, stop=10, num=5)

l

#### indices y slicing (sub_arrays)

In [ ]:
#los elementos de un array estan indexados, podemos acceder a ellos

array = np.arange(10)

print(array[5])

# o tambien acceder a un rango del array

print(array[:7])
print(array[5:])

![](_rsc\slicing.png)

#### Operaciones con arrays

In [12]:
a = np.arange(1,26)
b = np.linspace(1,100,25)

#Para operar dos arrays, primero estos deben ser de la misma longitud

suma = a + b

![](_rsc\suma.png)

In [ ]:
# mas operaciones

resta = a - b
multiplicacion = a * b
division = a / b

![](_rsc\operaciones.png)

In [ ]:
# producto por un escalar

producto = a * 5


![](_rsc\escalar.png)

In [ ]:
# otras funciones
suma_total = a.sum()
minimo = b.min()
maximo = suma.max()


## arrays vs listas

* 1. *Operaciones Vectorizadas:* NumPy realiza operaciones en matrices y arrays completos de datos, en lugar de iterar a traves de elemetos uno por uno(listas), esto acelera los calculos.


* 2. *Uso de Memoria Eficiente:* Los arrays de NumPy son mas compactos en memoria que las listas de python, lo que reduce la sobrecarga y mejora el rendimiento.


* 3. *Paralelizacion:* NumPy puede aprovechar la paralelizacion de hardware, como CPU multicore, para acelerar calculos.


* 4. *Funciones de agregacion y estadisticas*: Tambien nos proporciona funciones optimizadas para realizar calculos estadisticos y de agregacion en arrays numericos.

In [13]:
import numpy as np
import time

# Crear una lista de Python y un array de NumPy con 10 millones de elementos
lista_python = list(range(10000000))
array_numpy = np.arange(10000000)

# Realizar una operación simple: elevar todos los elementos al cuadrado
start_time = time.time()
lista_python_cuadrado = [x ** 2 for x in lista_python] #List comprehension
end_time = time.time()
print("Tiempo usando lista de Python:", end_time - start_time, "segundos")

start_time = time.time()
array_numpy_cuadrado = array_numpy ** 2
end_time = time.time()
print("Tiempo usando array de NumPy:", end_time - start_time, "segundos")


Tiempo usando lista de Python: 4.084692478179932 segundos
Tiempo usando array de NumPy: 0.048096418380737305 segundos


## Matrices

Puedes crear un array de NumPy pasandoles una lista de listas para crear un array de n dimensiones
(o una 'matriz n x n').

In [3]:
matrix = np.array([[1,2,3], [4,5,6], [7,8,9]])

matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

![](_rsc\matriz.png)

In [ ]:
#Para acceder a los elementos de una matriz es igual con la notacion de indices.
#ojo a la hora de hacer slicing

print(matrix[0,1])
print(matrix[1:3])
print(matrix[0:2, 0])

![](_rsc\np_matrix_indexing.png)

In [ ]:
#a una matriz tambien se le pueden aplicar los siguientes metodos

suma_m = matrix.sum()
max_m = matrix.max()
min_m = matrix.min()

![](_rsc\np_matrix_aggregation.png)

In [19]:
# podemos hacer la suma resta y multiplicacion de una matriz,
# para la suma y resta se hace la misma notacion, con la multiplicacion
# es asi

mult_matriz = matrix @ matrix

## Otras maneras de crear arrays

In [24]:
#crear arrays full de ceros 0

cero = np.zeros(10)
cero_matriz = np.zeros((3,5))

In [27]:
# se puede hacer lo mismo pero con puros 1

uno = np.ones(100)
uno_matriz = np.ones((10,5))

## Tamaño de un array 

In [28]:
# con la funcion shape, podemos saber el tamaño de un array.

uno.shape

(100,)

## `Reshape`

In [31]:
# con reshape podemos cambiar la forma de un array

x = np.arange(9)
print(x)

x.reshape(3,3)

[0 1 2 3 4 5 6 7 8]


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

Ya vimos que NumPy tiene un fuerte impacto en el rendimiento de nuestro equipo y tiempo de ejecucion de equipo, esta libreria es sumamente usada en diversos proyectos relacionados con analisis numerico, algebra lineal, machine learning, deep learning y mucho mas, para conocer numerosas aplicaciones de esta libreria visite el siguiente enlace:

## https://numpy.org/numpy-tutorials/

Y no olvidemos que siempreque trabajamos con una libreria hay que tener la documentacion a la mano

## https://numpy.org/doc/